export const GET_POKEMONS = "GET_POKEMONS";
export const GET_TYPES = "GET_TYPES";
export const GET_POKEMON_ID = "GET_POKEMON_ID";
export const GET_POKEMON_NAME = "GET_POKEMON_NAME";
export const POKEMON_ORDER = "POKEMON_ORDER";
export const POKEMON_FILTER = "POKEMON_FILTER";
export const POKEMON_TYPES = "POKEMON_TYPES";